# Generated by Django 3.0.6 on 2022-01-14 12:12

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bio', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(default='2016-03-03')),
                ('display_pic', models.ImageField(blank=True, default='/media/admin/default_user_dp/dp.jpg', null=True, upload_to=accounts.models.upload_location)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
